from distutils.core import setup

setup(name='django-mollie-api',
      version='0.1',
      description='Python/Django interface to Mollie.com payment API',
      long_description=open('README.rst').read(),
      author='Neven Falica, Paul Burt',
      author_email='neven.falica@felloz.com, paul.burt@gmail.com',
      license='BSD',
      classifiers=['Development Status :: 4 - Beta',
                   'Environment :: Web Environment',
                   'Framework :: Django',
                   'Intended Audience :: Developers',
                   'License :: OSI Approved :: BSD License',
                   'Operating System :: OS Independent',
                   'Programming Language :: Python',
                   'Topic :: Utilities'],
      url='https://github.com/elkarrde/django-mollie-api',
      download_url='https://github.com/elkarrde/django-mollie-api/downloads',
      packages=['django_mollie',
                'django_mollie.payment',
                'django_mollie.payment.management',
                'django_mollie.payment.management.commands'],
      data_files=[('django_mollie', ['payment/mollie_banklist.xml'])]
      )
